Repository dotnet/Nerdbank.GitVersioning, pull requests merged in 2020-09, with the labels that each got.

#503 Fix build integration tests in light of MSBuild 16.7
  src/NerdBank.GitVersioning.Tests/NerdBank.GitVersioning.Tests.csproj
Labels: auto-merge

#504 Merge v3.2 to master
  src/NerdBank.GitVersioning.Tests/NerdBank.GitVersioning.Tests.csproj
Labels: auto-merge

#502 Allow TeamCity to provide tag refs
  src/NerdBank.GitVersioning.Tests/BuildIntegrationTests.cs
  src/NerdBank.GitVersioning/CloudBuild.cs
  src/NerdBank.GitVersioning/CloudBuildServices/TeamCity.cs
  src/NerdBank.GitVersioning/CloudBuildServices/VisualStudioTeamServices.cs
Labels: auto-merge

#506 Add `--metadata` option list to `nbgv` commands
  src/nbgv/Program.cs
Labels: auto-merge

#507 Perf: Cache JSON parse results while computing height
  src/NerdBank.GitVersioning/GitExtensions.cs
  src/NerdBank.GitVersioning/SemanticVersion.cs
  src/NerdBank.GitVersioning/VersionFile.cs
  src/NerdBank.GitVersioning/VersionOptions.cs
  src/NerdBank.GitVersioning/VersionOracle.cs
Labels: enhancement

#508 Invoke `GetBuildVersion` MSBuild task only once per project (or per repo)
  doc/globalproperties_log.png
  doc/msbuild.md
  src/NerdBank.GitVersioning.Tests/NerdBank.GitVersioning.Tests.csproj
  src/Nerdbank.GitVersioning.Tasks/GetBuildVersion.cs
  src/Nerdbank.GitVersioning.Tasks/Nerdbank.GitVersioning.nuspec
  src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.Common.targets
  src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.Inner.targets
  src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets
Labels: auto-merge, enhancement

#510 Add node.js bin scripts to nb-gv NPM package
  src/nerdbank-gitversioning.npm/README.md
  src/nerdbank-gitversioning.npm/package.json
  src/nerdbank-gitversioning.npm/ts/core.ts
  src/nerdbank-gitversioning.npm/ts/index.ts
  src/nerdbank-gitversioning.npm/ts/main.ts
  src/nerdbank-gitversioning.npm/ts/npmVersion.ts
Labels: auto-merge, enhancement

#511 Reset versionHeightOffset in `nbgv prepare-release`
  src/NerdBank.GitVersioning.Tests/ReleaseManagerTests.cs
  src/NerdBank.GitVersioning/GitExtensions.cs
  src/NerdBank.GitVersioning/ReleaseManager.cs
Labels: auto-merge

#512 Improve `nbgv get-commits <version>` perf
  src/NerdBank.GitVersioning/GitExtensions.cs
  src/nbgv/Program.cs
Labels: auto-merge, enhancement

#515 Fix msbuild task handling of `ProjectPathRelativeToGitRepoRoot`
  src/NerdBank.GitVersioning/VersionOracle.cs
Labels: auto-merge, bug
